<?php

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly
}

if ( ! class_exists( 'Sandbox_Settings_Advanced', false ) ) :

/**
 * Sandbox_Settings_Advanced.
 */
class Sandbox_Settings_Advanced extends Sandbox_Settings_Page {

    /**
     * @var array|mixed|void
     */
    public $options = array();

	/**
	 * Constructor.
	 */
	public function __construct() {
		$this->id    = 'advanced';
		$this->label = __( 'Advanced', 'sandbox' );
        $this->options = get_option('sandbox_options', false);

		parent::__construct();
	}

    /**
     *  Advanced page notice text
     */
    public function get_upgrade_text(){
        $upgradeText = __('One Click Logins, SSH, SFTP, Instant PHP Switching, & More', 'sandbox');
        if (!empty(Sandbox::getInstance()->server_data['license']) && Sandbox::getInstance()->server_data['license']['plan_name'] == Sandbox::FREE_TRIAL_PLAN) {
            $upgradeText = sprintf(__('In %d days your installs will be moved to poopy.life'), Sandbox::getInstance()->getFreeTrialDaysLeft());
        }
        echo $upgradeText;
    }

	/**
	 * Get settings array.
	 *
	 * @return array
	 */
	public function get_settings() {
		return Sandbox::getInstance()->server_data;
	}

    /**
     * @param $key
     * @return mixed|string
     */
    public function getSetting($key){
        if ( Sandbox_API::getInstance()->is_poopy_site()){
            $value = '';
            for ($i = 0; $i < strlen($key); $i++){
                $value .= "&bull;";
            }
            if ($key == 'php_version'){
                $value = phpversion();
            }
            return $value;
        }
        $value = isset(Sandbox::getInstance()->server_data[$key]) ? Sandbox::getInstance()->server_data[$key] : '';
        if ($value){
            switch ($key){
                case 'server_web_host':
                    $value .= '.' . Sandbox_API::getInstance()->get_domain();
                    break;
                default:
                    break;
            }
        }
        switch ($key){
            case 'port':
                $value = '2222';
                break;
            default:
                break;
        }
        return $value;
    }

    /**
     * @return string
     */
    public function getOneClickUrl(){
        return $this->options['url'] . (Sandbox_API::getInstance()->is_poopy_site() ? '/&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;' : '?upass=' . $this->options['password']);
    }

	/**
	 * Save settings.
	 */
	public function save() {

	    if ( ! empty($_POST['sandbox_advanced_settings']) ){

            check_admin_referer('sandbox-settings');

            if (!$this->errors->get_error_codes()) { // no validation errors detected


            }
        }
	}

    /**
     *  Render advanced settings page
     */
    public function output() {

        Sandbox::getInstance()->server_data = Sandbox_API::getInstance()->get_sandbox_data();

        parent::output(); // TODO: Change the autogenerated stub
    }

}

endif;

return new Sandbox_Settings_Advanced();
